version: "3.7"

services:

  db:
    image: postgres:9.5
    container_name: meu-postgres
    volumes:
      - /Users/murillo/development/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - "minha-rede"
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=db_project_oauth2
         - PGDATA=/var/lib/postgresql/data/pgdata
         
  springbootapp:
    image: mupezzuol/springboot-oauth2-rbac
    container_name: meu-springbootapp
    ports:
      - "8080:8080"
    networks: 
      - "minha-rede"
    depends_on:
      - db

networks: 
  minha-rede:
    driver: bridge